#-------------------------------------------------------------------------------
# Copyright (c) 2026 RWTH Aachen University, Germany,
# Virtual Reality & Immersive Visualisation Group.
#-------------------------------------------------------------------------------

spec:
  inputs:
    unreal_version:
      description: The Unreal Engine version in the form of "major.minor"
      type: string
      regex: \d+\.\d+
      default: "5.7"
    build_type:
      description: The game build type.
      type: string
      options: ["DebugGame", "Shipping"]
      default: "DebugGame"
    number_of_old_versions:
      description: How many successful pipeline builds of this branch should be stored on the cluster.
      type: number
      default: 3
    custom_ndisplay_config:
      description: Custom nDisplay config stored on the cluster filesystem.
      type: string
      default: ""
    use_shared_cache_zen:
      description: Whether or not to use the remote cache server
      type: string
      options: ["true", "false"]
      default: "true"
    cluster_address:
      description: The address to the cluster host.
      type: string
      default: "cc-win.vr.rwth-aachen.de"
    plugin_dependencies:
      type: array
      description: Plugin repositories to additionally add to the generated project.
      default:
        - https://github.com/VRGroupRWTH/UnrealDTrackPlugin.git#master
        - https://git-ce.rwth-aachen.de/vr-vis/VR-Group/unreal-development/plugins/rwth-vr-cluster-plugin.git#dev/5.7


---

# The include file can be change to either be removed or reference a specific commit.

include:
  # include the component located in the current project from the current SHA
  # - component: $CI_SERVER_FQDN/$UNREAL_CI_PROJECT/generate-project@master
  #   inputs:
  #     unreal_version: $[[ inputs.unreal_version ]]
  - component: $CI_SERVER_FQDN/$UNREAL_CI_PROJECT/build-windows@master
    inputs:
      unreal_version: $[[ inputs.unreal_version ]]
      use_shared_cache_zen: $[[ inputs.use_shared_cache_zen ]]
      build_type: $[[ inputs.build_type ]]
      custom_ndisplay_config: $[[ inputs.custom_ndisplay_config ]]
  - component: $CI_SERVER_FQDN/$UNREAL_CI_PROJECT/generate-project@master
    inputs:
      unreal_version: $[[ inputs.unreal_version ]]
      plugin_dependencies: $[[ inputs.plugin_dependencies ]]
  - component: $CI_SERVER_FQDN/$UNREAL_CI_PROJECT/deploy@master
    inputs:
      unreal_version: $[[ inputs.unreal_version ]]
      cluster_address: $[[ inputs.cluster_address ]]
      number_of_old_versions: $[[ inputs.number_of_old_versions ]]

    
# In this file you are able to configure your plugins pipeline.
# If you want to customize something, either overwrite things that are defined in the shared_scripts repository,
# or remove the "extends" and write your own scripts
# 
# If you want your pipeline to run on every commit, just remove the "only" blocks. Keep in mind, that a build
# can take some time.
# 
# If you want to alter the unreal-building process two variables are defined for either changing the CLIENT_CONFIG or
# for adding EXTRA_ARGS to the building process
# 


stages:
  - analyze
  - generate
  - build
  - deploy

clang-format:
    image: registry.git-ce.rwth-aachen.de/vr-vis/vr-group/alpine-analyze:latest
    tags:
        - docker-executor
        - linux
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    variables:
        GIT_STRATEGY: fetch
        GIT_CHECKOUT: "true"
        GIT_DEPTH: "2"
    stage: analyze
    allow_failure: false
    script:
        - clang-format --version
        - git fetch --depth 1 origin $CI_MERGE_REQUEST_DIFF_BASE_SHA
        - echo $CI_MERGE_REQUEST_DIFF_BASE_SHA 
        - linter_errors=$(unbuffer git-clang-format --commit "$CI_MERGE_REQUEST_DIFF_BASE_SHA" *.h *.cpp -q --diff | grep -v --color=always "no modified files to format" || true)
        - echo "$linter_errors"
        - if [ ! -z "$linter_errors" ]; then echo "Detected formatting issues; please fix. Make sure you are using the same clang-format version! You can download it from the development section in this repo's wiki."; exit 1; else echo "Formatting is correct"; exit 0; fi

Generate_Project:
    rules: 
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      - if: $CI_COMMIT_TAG
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    extends: .Generate_Project_

Build_Windows:
    rules: 
      - if: $CI_PIPELINE_SOURCE == "web"
      - if: $CI_PIPELINE_SOURCE == "schedule"
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      - if: $CI_COMMIT_TAG
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    extends: .Build_Windows_
    tags:
        - windows
        - unreal
    variables:
        GIT_STRATEGY: none   
        GIT_CHECKOUT: "false"
        CLIENT_CONFIG: $[[ inputs.build_type ]]
    needs:
        - job: "Generate_Project"
          artifacts: true
    
#.Build_Linux:
#    rules: 
#      - if: $CI_PIPELINE_SOURCE == "web"
#      - if: $CI_PIPELINE_SOURCE == "schedule"
#      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#      - if: $CI_COMMIT_TAG
#      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#    extends: .Build_Linux_
#    tags:
#        - linux
#        - unreal
#        - docker-executor
#    variables:
#        GIT_STRATEGY: none   
#        GIT_CHECKOUT: "false"
#        # CLIENT_CONFIG: "Shipping"
#        CLIENT_CONFIG: $[[ inputs.build_type ]]
#    needs:
#        - job: "Generate_Project"
#          artifacts: true

Deploy_General:
  rules: 
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  extends: .Deploy_General_
  needs:
    - job: Build_Windows
      artifacts: true
